package com.seasonsread.app.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.util.ArrayList;

/**
 * Created by ZhanTao on 1/9/15.
 */
@DatabaseTable(tableName="feeds_list")
public class Feed extends BaseModel{
    public static final String ROW_ID = "_id";
    public static final String ROW_TITLE = "title";
    public static final String ROW_AUTHOR = "Author";
    public static final String ROW_ARTICLE_ID = "article_id";
    public static final String ROW_TYPE_ID = "type_id";
    public static final String ROW_HITNUM = "hitnum";
    public static final String ROW_CREATE_TIME = "createtime";
    public static final String ROW_IS_RESERVED = "is_reserved";

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true, columnName = ROW_ID)
    private int id;

    @DatabaseField(columnName = ROW_TITLE)
    private String title;
    @DatabaseField(columnName = ROW_AUTHOR)
    private String blog_name;
    @DatabaseField(columnName = ROW_CREATE_TIME)
    private String createtime;

    @DatabaseField(index = true, columnName = ROW_ARTICLE_ID)
    private int article_id;

    @DatabaseField(columnName = ROW_TYPE_ID)
    private int type_id;
    @DatabaseField(columnName = ROW_HITNUM)
    private int hitnum;
    @DatabaseField(columnName = ROW_IS_RESERVED)
    private int is_reserved;

    public Feed(){
        // needed by ormlite
    }

    public static class GsonRequestData{
        public ArrayList<Feed> feeds;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBlog_name() {
        return blog_name;
    }

    public void setBlog_name(String blog_name) {
        this.blog_name = blog_name;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public int getArticle_id() {
        return article_id;
    }

    public void setArticle_id(int article_id) {
        this.article_id = article_id;
    }

    public int getType_id() {
        return type_id;
    }

    public void setType_id(int type_id) {
        this.type_id = type_id;
    }

    public int getHitnum() {
        return hitnum;
    }

    public void setHitnum(int hitnum) {
        this.hitnum = hitnum;
    }

    public int getIs_reserved() {
        return is_reserved;
    }

    public void setIs_reserved(int is_reserved) {
        this.is_reserved = is_reserved;
    }
}
